### ISSUE TITLE
Callbacks break when device is announced multiple times

### ISSUE THREAD

**Issue by daenney** [hemtjanst/hemtjanst#1]
## Reproduce

* Announce a device
* Re-announce the same device
* Put a value on the `getTopic`

## Result
Hemtjänst will not update the corresponding accessory in HomeKit

## Workaround
Restart Hemtjänst

**Comment by bonan** [comment]
Issue is partly solved in 8ffc7bf

No new metadata will be pushed to homekit (i.e. if a feature is added/removed or model/serial is changed) until hemtjanst is restarted.
It seems that the homekit specification doesn't allow that in all cases either - needs investigation
