### ISSUE TITLE
light Switches and bulbs

### ISSUE THREAD

**Issue by ghost** [hemtjanst/hemtjanst#11]
great project 

i am working on adding touch light switches that can also be controlled over mqtt.
This allows humans to use them but also the house automation. 
They work over wifi, but also mqtt.

Sonoff hardware light switches
Mqtt tasmoto code: https://github.com/arendst/Sonoff-Tasmota

Upload firmware: https://github.com/arendst/Sonoff-Tasmota/wiki/Upload
No hardware soldering needed !

https://github.com/stefanwichmann/kelvin
Adjust diurnal ligths

LED bulbs
http://sonoff.itead.cc/en/products/residential/sonoff-b1
15 euro :)

**Comment by daenney** [comment]
I'm glad you like the project and we'll be happy to review any contributions. Since this isn't reall an issue, currently, I'm closing it for now. If you run into any implementation problems feel free to raise a new issue with the details and we can try and help you out!
