### ISSUE TITLE
Install fails?

### ISSUE THREAD

**Issue by abrownsword** [hemtjanst/hemtjanst#15]
Found some instructions and got further with the install, however now I get this:

> github.com/hemtjanst/hemtjanst/homekit/util
../src/github.com/hemtjanst/hemtjanst/homekit/util/accessory.go:71:10: undefined: accessory.TypeHumidifer
> github.com/hemtjanst/hemtjanst/messaging/flagmqtt
../src/github.com/hemtjanst/hemtjanst/messaging/flagmqtt/setup.go:108:19: multiple-value uuid.NewV4() in single-value context

Is anyone still paying attention to this project?

**Comment by daenney** [comment]
You need to use [`dep`](https://github.com/golang/dep) to get the dependencies. Just using a `go get` won't work, upstream libraries have made changes isnce. We don't track upstream all the time unless there's a need to upgrade, especially b/c hc and uuid have a habit of changing things.

```
git clone ...
cd <dir>
dep ensure
go build
```
