### ISSUE TITLE
Change MQTT discover/announce flow

### ISSUE THREAD

**Issue by bonan** [hemtjanst/hemtjanst#4]
## Current behavior
1. Bridge sends a persistent message to `discover` on startup
2. Clients subscribe to `discover` on startup
3. Clients publish their meta to `<baseTopic>/meta` on startup
4. Clients sends their own base topic name to `announce` every time a discover message is received
5. Bridge is subscribed to `announce`, when receiving a message, `<payload>/meta` is subscribed to

## Suggestion 
1. Does not change
2. Does not change
3. On receiving a message from `discover`, clients publish their meta with persistence to `announce/<baseTopic>`
4. Bridge is subscribed to `announce/#`, any messages received are parsed as device metadata

## Benefits
* The bridge will get information about all previous devices upon startup, even if they're not currently available. MQTT server acts as a database, instead of the bridge having to store all seen devices
* Any devices discovered before `discover` is sent can be marked as offline until receiving a new update
* One less subscription for the bridge per device
* A client can be permanently removed by publishing an empty payload with persistence to its announce-topic

## Drawbacks
* Breaks all current implementations
* Clients have to compile and send meta for every discovery, potentially requiring more resources and bandwidth.
* If multiple bridges are running, all of them have to parse and compare received meta for all devices every time another bridge makes a discover request.

**Comment by daenney** [comment]
Sounds good to me. I'd rather do this change now than later as there's currently very few Hemtjänst compatible clients. Breaking things now is easier.

Considering how small meta is and this is geared towards use on home networks, not widely deployed sensor networks with constrained throughput, the extra few bytes from sending meta don't seem like a problem.

W.r.t the cost of generating meta. I expect most implementations will be bridging other bridges (like Trådfri). That software can run on computers that have plenty of cycles to spare and even a Raspberry Pi wouldn't break a sweat on this. HomeKit allows for max 100 devices to be bridged, I don't foresee any issues. For super-tiny clients like a NodeMCU exposing a sensor, it's so few devices they expose that I don't see this turning into a problem.

**Comment by daenney** [comment]
:shipit:

**Comment by bonan** [comment]
- [ ] Update documentation
- [ ] Verify that the device package still can be used as a client library
- [ ] Remove debugging outputs in `homekit/device_holder.go`?
- [ ] Verify that `util.HexToInt64` works as intended
